spring:
  config:
    import:
      - "bot.yml"
      - "scenarios.${bot.scenario:default}.yml" # Changed dynamic import
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

game:
  gameSettings:
    maxScenariosPerGame: 15
