spring:
  config:
    import:
      - "bot.yml"
      - "scenarios.yml"
      - "resources.yml"
      - "messages.yml"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

game:
  gameSettings:
    maxScenariosPerGame: 15
