spring:
  config:
    import:
      - "bot.yml"
      - "scenarios.${BOT_SCENARIO:default}.yml"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

game:
  gameSettings:
    maxScenariosPerGame: 15
