spring:
  config:
    import:
      - "bot.yml"
      - "scenarios.yml"
      - "resources.yml"
      - "messages.yml"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

game:
  gameSettings:
    maxScenariosPerGame: 15
